# Set update schedule for each package manager

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates on Monday
      day: "monday"
    target-branch: "develop"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates on Monday
      day: "monday"
    target-branch: "develop"
    # Labels on pull requests for security and version updates
    labels:
      - "composer dependencies"
