name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          script: |
            cd ${{ secrets.PATH }}
            git checkout main && git checkout .
            git pull ${{ secrets.REPO }}
            composer install --no-interaction --no-progress --optimize-autoloader
            php artisan migrate:fresh --seed --quiet
            npm install --silent
            npm run dev
